Feature/image inference
platiagro/web-ui pull request #187
Opened 2020-09-11 13:16 UTC by samborba

Test Inference for Images
- add support for inference of jpg, jpeg and png extension files
- display image instead of the csv table whenever the response is coded in base64 and type image/jpeg

2020-09-11 15:28 UTC, fberanizo requested changes

2020-09-11 15:28 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/_/index.js
> +      if (base.includes('image/jpeg') && pattern.test(content)) return true;
@samborba em outra parte do código tem .jpg', '.jpeg', '.png' mas aqui só está jpeg. pode ser image/png também, não?

2020-09-11 15:28 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/_/index.js
> +  );
@samborba remova o console.log, por favor.

2020-09-11 15:28 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/_/index.js
> +        {isBase64Encoded(experimentInference.ndarray) ? (
@samborba acho que o `isBase64Encoded` não funcionou pro teste que fiz:
![image_not_shown](https://user-images.githubusercontent.com/1791381/92944316-34365080-f42a-11ea-88db-028fa63f8e30.PNG)

2020-09-11 15:31 UTC, fberanizo commented
@samborba Tenho uma sugestão:
se receber um base64 e não for image/... dá pra fazer um botão de download?

2020-09-11 15:33 UTC, samborba commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/_/index.js
> +      if (base.includes('image/jpeg') && pattern.test(content)) return true;
@fberanizo aqui esta sendo validado o retorno do API do Seldon. Posso então deixar que exiba qualquer formato de image?

2020-09-11 16:04 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/_/index.js
> +      if (base.includes('image/jpeg') && pattern.test(content)) return true;
@samborba isso. Exiba outros formatos também.

2020-09-12 04:09 UTC, samborba commented
> @samborba Tenho uma sugestão:
> se o predictor retornar um base64 e não for image/... dá pra fazer um botão de download?

Fabio, por ora eu fiz algo nesse estilo:
![code-display](https://user-images.githubusercontent.com/56934233/92986912-89a74780-f494-11ea-9fe2-35c65af235aa.png)

Teriamos que definir melhor esta tela.

2020-09-14 11:33 UTC, fberanizo approved these changes
LGTM

2020-09-14 11:34 UTC, merged