CopyFrom implemented to copy operators and move on to the new experim…
platiagro/web-ui pull request #190
Opened 2020-09-14 11:38 UTC by AlendeGeraldo

…ent to be created

2020-09-14 13:07 UTC, fberanizo requested changes

2020-09-14 13:07 UTC, fberanizo commented on src/store/experiment/actions.js
> +    .catch((err) => {});
@AlendeGeraldo faltou uma validação caso o novo nome do experimento já exista. Essa validação existe no "Renomear" (imagem abaixo):
![image](https://user-images.githubusercontent.com/1791381/93089326-85845100-f671-11ea-9875-f6ab2bf12b13.png)

2020-09-15 20:24 UTC, fberanizo requested changes

2020-09-15 20:24 UTC, fberanizo commented on src/store/experiment/actions.js
> +const createExperimentFail = (error, duplilcate) => (dispatch) => {
@AlendeGeraldo essa solução funciona, porém reusar o `createExperimentRequest` e  `createExperimentFail` tem uma consequência inesperada. 
Este trecho do createExperimentFail faz aparecer uma mensagem de erro no modal de criar novo experimento. 
A funcionalidade de duplicar não deveria causar este tipo de coisa.
```
     dispatch({
        type: actionTypes.CREATE_EXPERIMENT_FAIL,
        errorMessage,
      });
```
![image](https://user-images.githubusercontent.com/1791381/93259992-1729b680-f777-11ea-847e-ba66c0e65b8c.png)

## Sugiro criar novos métodos neste arquivo `duplicateExperimentRequest`,  `duplicateExperimentFail ` e `duplicateExperimentSuccess` e manter o código do `createExperimentFail ` e `createExperimentRequest` sem alteração.

2020-09-16 17:47 UTC, AlendeGeraldo commented on src/store/experiment/actions.js
> +const createExperimentFail = (error, duplilcate) => (dispatch) => {
Acredito que não seria uma boa solução já que teria que duplicar muitos métodos, para solucionar esse problema foi criado uma nova action para resolver esse problema.

2020-09-17 16:27 UTC, samborba requested changes
@AlendeGeraldo recebo erro 500 ao duplicar um experimento, mas se eu der reload na tela o experimento vai ter sido criado, porém sem o conteúdo do copyFrom:
![image](https://user-images.githubusercontent.com/56934233/93499280-2f214780-f8e9-11ea-802e-ac0f1cff5562.png)
![image](https://user-images.githubusercontent.com/56934233/93499392-4b24e900-f8e9-11ea-9a4b-7685926758ec.png)

2020-09-21 14:07 UTC, fberanizo requested changes

2020-09-21 14:07 UTC, fberanizo commented on src/store/experiment/actions.js
> +  duplcate,
@AlendeGeraldo ajuste a escrita das variáveis `duplcate` -> `duplicate`.

2020-09-21 14:07 UTC, fberanizo commented on src/store/experiment/actions.js
> + * @param duplcate
@AlendeGeraldo ajuste a escrita das variáveis `duplcate` -> `duplicate`.
Ah... está repetido ,só deve ter 1 linha.

2020-09-21 14:07 UTC, fberanizo commented on src/store/experiment/actions.js
> +    .catch((error) => dispatch(createExperimentFail(error, duplcate)));
@AlendeGeraldo ajuste a escrita das variáveis `duplcate` -> `duplicate`.

2020-09-21 14:07 UTC, fberanizo commented on src/store/experiment/actions.js
> + * @param duplilcate
@AlendeGeraldo ajuste a escrita das variáveis `duplilcate` -> `duplicate`.

2020-09-21 14:07 UTC, fberanizo commented on src/store/experiment/actions.js
> +const createExperimentFail = (error, duplilcate) => (dispatch) => {
@AlendeGeraldo ajuste a escrita das variáveis `duplilcate` -> `duplicate`.

2020-09-21 14:07 UTC, fberanizo commented on src/store/experiment/actions.js
> +    if (errorMessage.includes('name already exist') && !duplilcate) {
@AlendeGeraldo ajuste a escrita das variáveis `duplilcate` -> `duplicate`.

2020-09-23 17:43 UTC, fberanizo approved these changes
👍

2020-09-24 17:21 UTC, fberanizo approved these changes

2020-09-24 17:29 UTC, merged