Fix/get featuretypes
platiagro/web-ui pull request #196
Opened 2020-09-16 00:27 UTC by samborba

- add function to validate whenever a dataset has featuretypes or not
- reuse response from GET request when selecting an operator to fill "featuretypes" of the dataset state, avoiding unnecessary request
- enable button whenever a dataset has featuretypes, otherwise, disable it

2020-09-16 01:14 UTC, fberanizo requested changes
@samborba os problemas lá do outro PR parecem resolvidos, mas notei mais algumas coisas:
- Quando eu adiciono um Conjunto de Dados  ao fluxo ele está com o status 'Ready'/'Setted Up' (deveria ser Unset). 
- O nome do conjunto de dados não é exibido pra fluxos já executados:
![image](https://user-images.githubusercontent.com/1791381/93280654-8962c100-f7a0-11ea-8201-b43bae615f74.png)
![image](https://user-images.githubusercontent.com/1791381/93280675-94b5ec80-f7a0-11ea-9b21-2028469417f6.png)

Parece que o 'Upload de arquivo' está com problemas para executar, mas este é outro bug, que vou ver com o @shiguemi32 .

2020-09-16 17:19 UTC, samborba commented
> @samborba os problemas lá do outro PR parecem resolvidos, mas notei mais algumas coisas:
> 
> * Quando eu adiciono um Conjunto de Dados  ao fluxo ele está com o status 'Ready'/'Setted Up' (deveria ser Unset).
> * O nome do conjunto de dados não é exibido pra fluxos já executados:
>   ![image](https://user-images.githubusercontent.com/1791381/93280654-8962c100-f7a0-11ea-8201-b43bae615f74.png)
>   ![image](https://user-images.githubusercontent.com/1791381/93280675-94b5ec80-f7a0-11ea-9b21-2028469417f6.png)
> 
> Parece que o 'Upload de arquivo' está com problemas para executar, mas este é outro bug, que vou ver com o @shiguemi32 .

O bug de não exibir o nome do conjunto de dados executados está sendo causado pelo backend. Já estou arrumando!

2020-09-17 00:02 UTC, fberanizo requested changes

2020-09-17 00:02 UTC, fberanizo commented on src/store/operator/actions.js
> -      let settedUp = utils.checkOperatorSettedUp(operator);
@samborba esta linha ainda é necessária para componentes que já são settedUp por padrão (por ex, um componente sem parâmetros).

2020-09-17 15:47 UTC, fberanizo approved these changes

2020-09-17 15:47 UTC, merged