Adds Support for Seldon Text and Binary Responses
platiagro/web-ui pull request #215
Opened 2020-09-23 19:57 UTC by samborba

- add option to copy text and string from base64 encoded unsupported file, and thus ui success notification
- add support for video media file
- changes initial state of Sheldon's response object to make it more generic

2020-09-24 17:15 UTC, fberanizo requested changes

2020-09-24 17:15 UTC, fberanizo commented on src/utils.js
> +      const [base, content] = response.binData.split(',');
@samborba pelos meus testes o `binData` tem que ser só o base64, sem o prefixo do data:.., senão o seldon dá pau pq ele já faz o base64decode (de todo o binData) inclusive o prefixo.

O `strData` deu certo com o dataURI, mas agora não sei como é a melhor forma de lidar com isso aqui no front-end...
Podemos passar só o base64, e evitar fazer o base64encode no nosso código. Porém, o tipo do dado ficaria desconhecido...

@alvesfelipe tem alguma sugestão?

2020-09-24 17:15 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/_/index.js
> +          </div>
@samborba acho que esses botões poderiam aparecer para todos os retornos...

2020-09-24 21:48 UTC, samborba commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/_/index.js
> +          </div>
@fberanizo até mesmo para as predições tabulares?

2020-09-25 00:34 UTC, samborba commented on src/utils.js
> +      const [base, content] = response.binData.split(',');
@fberanizo existe um [método de identificar o tipo de uma base64](https://en.wikipedia.org/wiki/List_of_file_signatures), mas não é 100% confiável...

2020-09-25 15:38 UTC, fberanizo commented
@samborba conforme conversamos: apenas mude o envio de data URI para strData.

2020-09-25 15:45 UTC, fberanizo requested changes

2020-09-25 15:45 UTC, fberanizo commented on src/utils.js
> +  const [base] = response.binData.split(',');
@samborba se a resposta for binData sempre será só o base64.

2020-09-25 15:45 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/UploadInferenceTestButton/index.js
> +              binData: e.target.result,
@samborba aqui é só alterar de binData para strData (dataURI + base64).

2020-09-25 15:45 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/UploadInferenceTestButton/index.js
> +    accept: ['.csv', '.jpg', '.jpeg', '.png', '.webm', '.mp4'],
@samborba se você aceitar qquer tipo de arquivo, pode enviá-los como binStr (só o base64).

2020-09-25 15:45 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/UploadInferenceTestButton/index.js
>              };
ok, pode ser strData também...

mas para outros types, use binData (envie só o base64)

2020-09-28 12:36 UTC, fberanizo requested changes

2020-09-28 12:36 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/UploadInferenceTestButton/index.js
> +    accept: ['text/*', 'image/*', 'video/*'],
@samborba `accept: ['text/*', 'image/*', 'video/*'],` não causa o efeito desejado. Apesar do `text/*`, `.csv` não aparece entre as opções de arquivos. Sugiro remover o text/*. 
`audio/*` também parece legal adicionar. Ou deixar * ...
![image](https://user-images.githubusercontent.com/1791381/94431350-8b972900-016b-11eb-84ad-bee613d45902.png)

2020-09-28 12:36 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/UploadInferenceTestButton/index.js
> +          if (isImageOrVideo || (type === 'text' && subtype !== 'csv')) {
@samborba quando testei com um CSV foi enviado um `binData`. Acho que `type === 'text' && subtype !== 'csv')` não funciona. No meu teste o `type` identificado foi '' e o subtype `undefined`.

2020-09-28 12:36 UTC, fberanizo commented on src/utils.js
> +};
Este `try` `catch` é só por causa do `.match(/[^:]\w+\/[\w-+\d.]+(?=;|,)/)[0]` ?
Se for isso, faça um `if != null`  com o retorno do match.

2020-09-28 15:52 UTC, fberanizo requested changes

2020-09-28 15:52 UTC, fberanizo commented on src/utils.js
> +      .match(/[^:]\w+\/[\w-+\d.]+(?=;|,)/)[0]
@samborba este [0] é potencialmente perigoso e pode causar `TypeError: null has no properties` se o match retornar null (ex: quando strData não é dataURI). 

Conforme eu disse no outro comentário, você pode jogar o resultado do match para uma variável e fazer um `if (!= null)`

2020-09-28 15:52 UTC, fberanizo commented on src/components/Content/ImplantedExperimentsContent/ImplantedExperimentsTable/UploadInferenceTestButton/index.js
> +          } else if (file.type === 'text/csv') {
@samborba pra mim continua não funcionando... 
Todos os arquivos .csv,.txt que faço upload possuem `file.type == ""`, no Chrome e Firefox:
![image](https://user-images.githubusercontent.com/1791381/94454990-f440ce80-0188-11eb-86aa-279d89af61f8.png)
![image](https://user-images.githubusercontent.com/1791381/94455038-03c01780-0189-11eb-84d1-ea7dec589c05.png)

Talvez seja necessário usar uma biblioteca como esta: https://github.com/bevry/istextorbinary

Mas fique a vontade para buscar soluções.

2020-09-29 17:21 UTC, fberanizo approved these changes
👍

2020-09-29 17:22 UTC, merged