Feature/add flow connections
platiagro/web-ui pull request #221
Opened 2020-09-28 18:53 UTC by SchafferCPqD

Change arrow lib and create new connection and drag components.

2020-09-28 20:15 UTC, fberanizo requested changes

2020-09-28 20:15 UTC, fberanizo commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +    console.log(`${task.id} dragged to`, task.position);
@SchafferCPqD remova os `console.log`, por favor.

2020-09-28 20:15 UTC, fberanizo commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +      onConnectStart={() => setConnectClass('Connecting')}
Crashou quando eu troquei de experimento (clicando na aba):

Entrei neste (ok):
http://localhost:3000/projetos/d9f98ba3-62f4-4c87-bb82-6b47fed44b75/aaf0f1d2-3897-40fa-a2b2-893d749f24bf
![image](https://user-images.githubusercontent.com/1791381/94481274-d9348580-01ad-11eb-9acd-0dfe307f7c23.png)


Troquei para este (deu pau):
http://localhost:3000/projetos/d9f98ba3-62f4-4c87-bb82-6b47fed44b75/a1fa26d9-834d-4cd4-a484-de00c8037125
![image](https://user-images.githubusercontent.com/1791381/94481444-1567e600-01ae-11eb-9708-30361a4e951c.png)


@SchafferCPqD verifique por favor.

2020-09-28 20:18 UTC, SchafferCPqD commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +    console.log(`${task.id} dragged to`, task.position);
Esses eu deixei por que vamos usar jájá, é a função handle para salvar no backend o posicionamento e para conectar as tarefas.

2020-09-28 20:31 UTC, SchafferCPqD commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +      onConnectStart={() => setConnectClass('Connecting')}
Acho que faz parte daquilo te informei mais cedo, aconteceu um erro assim antes, mas não aconteceu mais. Aqui agora mesmo, a troca ocorreu normalmente. Acho que não tem relação com a parte do fluxo, mas é interessante verificar melhor.

2020-09-28 20:32 UTC, SchafferCPqD commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +      onConnectStart={() => setConnectClass('Connecting')}
Ah gostaria de ver o que o erro fala, ele deve aparecer na tela mesmo, não no console. Se aparecer, pega um print dele.

2020-09-28 20:49 UTC, fberanizo commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +      onConnectStart={() => setConnectClass('Connecting')}
Iche, eu criei um projeto novo e deu outra coisa quando fui adicionar um 2o experimento:
![image](https://user-images.githubusercontent.com/1791381/94484519-f0c23d00-01b2-11eb-87fb-d55680526f43.png)

2020-09-28 21:48 UTC, fberanizo commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +      onConnectStart={() => setConnectClass('Connecting')}
O 1o erro ficou na tela branca mesmo :(
É alguma coisa com essa conf de cards:
![image](https://user-images.githubusercontent.com/1791381/94489635-31be4f80-01bb-11eb-8bd6-9051c374ee02.png)

2020-09-29 16:37 UTC, fberanizo commented on src/components/Content/ProjectContent/Experiment/ExperimentFlow/_/index.js
> +      onConnectStart={() => setConnectClass('Connecting')}
Nos testes com ambiente docker os bugs não foram reproduzidos. Então vou colocar como resolvido.

2020-09-29 16:38 UTC, fberanizo approved these changes

2020-09-29 16:38 UTC, merged