Fix send null to parameter typer feature
platiagro/web-ui pull request #231
Opened 2020-10-01 19:35 UTC by shiguemi32

2020-10-01 20:14 UTC, fberanizo requested changes

2020-10-01 20:14 UTC, fberanizo commented on src/utils.js
> +          ? null
@shiguemi32 ainda bem que deu pra achar o erro...mas esse método tá ilegível com tanto operador ternário ? :  XD

Dá pra fazer uns if tradicionais e adicionar uns comentários, por favor?

2020-10-01 20:22 UTC, shiguemi32 commented on src/utils.js
> +          ? null
Claro pode deixa que eu arrumo

2020-10-06 18:54 UTC, fberanizo requested changes

2020-10-06 19:02 UTC, shiguemi32 commented on src/store/operators/actions.js
>      for (const operator of operatorsWithFeatureParameter) {
@fberanizo ele é usado para guardar todos os operadores que possuem parâmetro tipo feature

se o operador possuir ele adiciona no array operatorsWithFeatureParameter 
https://github.com/platiagro/web-ui/blob/1c72086b7f8e2ebf2114cfc18bef5e4dd37af351/src/store/operators/actions.js#L176

2020-10-06 20:12 UTC, fberanizo commented on src/store/operators/actions.js
>      for (const operator of operatorsWithFeatureParameter) {
blz! :) não tinha visto esta linha. obrigado!

2020-10-06 20:12 UTC, fberanizo approved these changes

2020-10-06 20:12 UTC, merged