Removed the loading on operators
platiagro/web-ui pull request #232
Opened 2020-10-01 20:22 UTC by hugooliv4

Removed the load on experiments add/remove operators.

2020-10-02 00:54 UTC, fberanizo requested changes
@hugooliv4 e @cedric-matheus pelo que testei o comportamento implementado foi:

(1) arrastar -> [acionar o backend sem loading] -> não exibir card enquanto backend não termina -> exibir card após backend terminar

(2) clicar em delete -> [acionar o backend sem loading] -> continuar exibindo card enquanto backend não termina -> remover card após backend terminar

Não ficou muito legal o feedback visual dessa forma. :(

---
Minha sugestão é 
(1) exibir o card enquanto o backend está rodando
(2) remover o card enquanto o backend está rodando

Em caso de erro no backend:
(1) remover o card (do front) e exibir popup de erro
(2) readicionar o card removido (do front) e exibir popup de erro

**Caso seja muito complicado, podemos deixar como estava anteriormente, com loading.**

2020-10-02 00:54 UTC, fberanizo commented on src/store/operators/actions.js
> + * @param withLoading
@hugooliv4 mantenha o padrão os docs, por favor, e adicione o tipo: `* @param {Boolean} withLoading`

2020-10-02 00:54 UTC, fberanizo commented on src/store/operators/actions.js
> +  if (withLoading) dispatch(operatorParameterLoadingData());
@hugooliv4 coloca chaves nos ifs, por favor, mesmo que seja apenas um comando. Isso ajuda a deixar o código mais legível:
```
  if (withLoading) {
    dispatch(operatorParameterLoadingData());
  }
 ```

2020-10-08 18:51 UTC, fberanizo commented
@hugooliv4 conforme conversado, esta funcionalidade foi despriorizada, devido à complexidade e tempo disponíveis.

O PR vai permanecer aberto, mas vamos concluí-lo em outra sprint.

2021-06-11 19:30 UTC, cedric-matheus commented
@fberanizo

Ainda existe a necessidade de deixar esse PR aberto?

2021-06-11 19:37 UTC, fberanizo commented
> @fberanizo
> 
> Ainda existe a necessidade de deixar esse PR aberto?

depois do PR do Schaffer, não mais :)

2021-06-11 19:37 UTC, closed without merging