Compare result modal
platiagro/web-ui pull request #258
Opened 2020-10-21 19:06 UTC by shiguemi32

2020-10-22 19:03 UTC, fberanizo requested changes

2020-10-22 19:03 UTC, fberanizo commented on src/components/Content/ContentHeader/ExperimentButtons/index.js
> +  handleCompareResultsClick,
@shiguemi32 Renomeie por favor o `handleClick` -> `handleDeploymentClick` para ficar mais claro que é o botão de preparar para implantação.

O que você acha de mudar as funções para o padrão `on...` ao invés de `handle...` me parece mais comum (e está meio fora de padrão na plataforma).
Pode ser algo assim..
```
<ExperimentButtons 
onCompareResultsClick={handleCompareResultsClick}
onDeploymentClick={handleDeploymentClick}
/>
```

2020-10-22 19:38 UTC, shiguemi32 commented on src/store/compareResults/actions.js
> +};
Deixa tudo na store ui/ então?
Precisa fica criando um método pra seta true e outro pra false?

2020-10-23 17:04 UTC, fberanizo approved these changes
:)

2020-10-23 17:04 UTC, merged