Deployed flows within projects details
platiagro/web-ui pull request #274
Opened 2020-11-10 19:44 UTC by shiguemi32

2020-11-11 12:00 UTC, fberanizo requested changes

2020-11-11 12:08 UTC, shiguemi32 commented on src/components/Content/ImplantedExperimentsContent/_/index.js
> +} from 'containers';
Eu vo remove este arquivo na hora que eu tira a implantação do menu

2020-11-11 16:07 UTC, fberanizo requested changes
@shiguemi32 pode ajustar mais alguma coisas, por favor:
### 10.50.11.116
![image](https://user-images.githubusercontent.com/1791381/98834251-bd173b80-241d-11eb-80ca-035ddd7c8837.png)
### Figma
![image](https://user-images.githubusercontent.com/1791381/98834616-2bf49480-241e-11eb-8214-a95c11e6a25a.png)


- Adicione padding ao `DeploymentsTable`
- Substitua os textos "Deletar", Logs e Testar o Fluxo por ícone + Tooltip
- Mapeie os status para texto (em português): `Running` -> `Em implantação`, `Failed` -> `Falhou`, `Success` -> `Sucesso`

2020-11-12 13:07 UTC, fberanizo approved these changes
👍

2020-11-12 13:07 UTC, merged