Feature/standardize action names
platiagro/web-ui pull request #277
Opened 2020-11-13 15:00 UTC by AlendeGeraldo

2020-11-13 17:07 UTC, fberanizo requested changes

2020-11-13 17:07 UTC, fberanizo commented on src/containers/DatasetUploadInputBlockContainer/DatasetUploadInputBlockContainer.jsx
> +  fetchDeleteDatasetRequest,
@AlendeGeraldo `fetchSelectDataset` -> `updateSelectedDatasetRequest`
`fetchStartGoogleDatasetUpload` -> `createGoogleDatasetRequest`
`fetchDeleteDatasetRequest` -> `deleteDatasetRequest`

2020-11-13 17:07 UTC, fberanizo commented on src/containers/DeploymentsTableContainer/DeploymentsTableContainer.jsx
> +  fetchDeleteDeployedExperiment,
@AlendeGeraldo `fetchDeployExperimentLogs` -> `fetchDeploymentLogsRequest`
`fetchDeleteDeployedExperiment` -> `deleteDeploymentRequest`

2020-11-13 17:07 UTC, fberanizo commented on src/containers/HeaderProjectDetailsContainer/HeaderProjectDetailsContainer.jsx
> +import { fetchDeleteProject } from 'store/projects/actions';
@AlendeGeraldo  `fetchEditProjectNameRequest` -> `updateProjectNameRequest`
`fetchDeleteProject` -> `deleteProjectRequest`

2020-11-13 17:07 UTC, fberanizo commented on src/containers/InferenceTestResultModalContainer/InferenceTestResultModalContainer.jsx
> +import { fetchDeployExperimentLogs } from 'store/deploymentLogs/actions';
@AlendeGeraldo `fetchDeployExperimentLogs` -> `fetchDeploymentLogsRequest`

2020-11-13 17:07 UTC, fberanizo commented on src/store/compareResults/actions.js
> +export const fetchAddCompareResult = (projectId) => {
@AlendeGeraldo `fetchAddCompareResult ` -> `createCompareResultRequest`

2020-11-13 17:07 UTC, fberanizo commented on src/store/compareResults/actions.js
> +export const fetchDeleteCompareResult = (projectId, id) => {
@AlendeGeraldo `fetchDeleteCompareResult` -> `deleteCompareResultRequest`

2020-11-13 17:07 UTC, fberanizo commented on src/store/dataset/actions.js
> +import { fetchClearOperatorsFeatureParametersRequest } from '../operators/actions';
@AlendeGeraldo `fetchSetOperatorParametersRequest` -> `updateOperatorParametersRequest`
`fetchClearOperatorsFeatureParametersRequest` -> `updateOperatorParametersRequest`

2020-11-13 19:36 UTC, AlendeGeraldo commented on src/store/dataset/actions.js
> +const dataSetColumnsSuccess = (response) => (dispatch) => {
Sim deveria continuar.

2020-11-13 20:36 UTC, AlendeGeraldo commented on src/store/dataset/actions.js
> +import { fetchClearOperatorsFeatureParametersRequest } from '../operators/actions';
Os imports aqui darão conflitos por serem o mesmo nome e de local diferente.

2020-11-24 14:49 UTC, cedric-matheus requested changes
Projetos não estão carregando.

2020-12-30 17:36 UTC, closed without merging