Upload de CSV com vírgulas no valor das colunas
platiagro/web-ui pull request #286
Opened 2020-11-25 14:25 UTC by AlendeGeraldo

2020-11-25 17:30 UTC, fberanizo requested changes

2020-11-25 17:30 UTC, fberanizo commented on src/services/DeploymentsApi.js
> +  form.append('url', `/deployments/${id}/api/v1.0/predictions`);
@AlendeGeraldo a URL completa é recebida do backend e deveria ser enviada neste serviço. Já estava errado anteriormente, vamos aproveitar para ajustar.
Troque o parâmetro `id` por `url` aqui e o `form.append('url', url);`

Será necessário alterar em outros arquivos:
https://github.com/platiagro/web-ui/blob/e644bdf96436677bf364414db36d9587c2cd233c/src/components/Content/ProjectDetailsContent/DeploymentsTable/DeploymentsTable.jsx#L92-L101

https://github.com/platiagro/web-ui/blob/e644bdf96436677bf364414db36d9587c2cd233c/src/containers/DeploymentsTableContainer/DeploymentsTableContainer.jsx#L17-L30

https://github.com/platiagro/web-ui/blob/e644bdf96436677bf364414db36d9587c2cd233c/src/store/testExperimentInference/actions.js#L20-L44

Em ambos você deverá passar a URL ao invés do experimentId/deployId

2020-11-25 17:30 UTC, fberanizo commented on src/services/DeploymentsApi.js
> +  return seldonApi.post(`deployments/seldon/test`, form);
@AlendeGeraldo como a URL é completa, com http://..., o seldonApi pode ser substituído por `axios.post`

2020-11-26 13:38 UTC, AlendeGeraldo commented on src/services/DeploymentsApi.js
> +  return seldonApi.post(`deployments/seldon/test`, form);
@fberanizo Acredito que não a url completa é a da linha 33, segundo o seu comentário anterior de alterar o id pela url.

2020-11-26 15:09 UTC, fberanizo requested changes

2020-11-26 15:09 UTC, fberanizo commented on src/components/Content/ProjectDetailsContent/DeploymentsTable/DeploymentsTable.jsx
> +              onTestInference(urlSeldonTest(record.experimentId), file)
@AlendeGeraldo eu acho que se você usar `record.url` você tem acesso à URL e não precisa do `urlSeldonTest`. Teste isso, por favor.

2020-12-11 12:21 UTC, fberanizo approved these changes
👍 Tá ok!

Vou dar merge assim que o backend estiver ok :)

2021-01-15 15:55 UTC, closed without merging