Deployments tabs (component and container)
platiagro/web-ui pull request #301
Opened 2020-12-11 18:36 UTC by shiguemi32

2020-12-14 11:23 UTC, fberanizo requested changes
@shiguemi32 pode criar por favor os .md para ficar no estilo do styleguide, que o @cedric-matheus indicou? 
Mais ou menos como este aqui:
https://github.com/platiagro/web-ui/tree/master/src/components/MonitoringImagePlaceholder

Pra ver se está tudo ok, use o comando `yarn styleguide`. Talvez precise mudar a extensão dos arquivos de .js para .jsx ... aqui pra mim apareceu assim:
![image](https://user-images.githubusercontent.com/1791381/102075553-2acfd200-3de5-11eb-9a62-df0207011383.png)

2020-12-14 13:24 UTC, fberanizo requested changes
@shiguemi32 acho que pode ter .md pro `NewTabButton`,  `NewTabModal` e `Tab` também

2020-12-16 13:23 UTC, fberanizo requested changes
@shiguemi32 olhando o styleguide percebi que o `Tab` é conjunto de abas (antd TabPane) e `Tabs` é a barra com as abas + botão de nova aba + modal de nova aba.
Estes nomes podem confundir um pouco. Eu mesmo, achei que o `Tab` era uma aba só.
O que você acha de renomear `Tab` -> `Tabs` ; e `Tabs` -> `???`

2020-12-16 13:23 UTC, fberanizo commented on src/components/Tabs/DraggableTabs/index.js
> +  handleMoveTab: PropTypes.func.isRequired,
@shiguemi32 aqui também pode ser `onMoveTab`

2020-12-16 13:23 UTC, fberanizo commented on src/components/Tabs/NewTabButton/NewTabButton.component.jsx
> +  handleClick: PropTypes.func.isRequired,
@shiguemi32 `onClick` (neste arquivo e no exemplo .md).

2020-12-16 13:23 UTC, fberanizo commented on src/components/Tabs/NewTabModal/NewTabModal.component.jsx
> +};
@shiguemi32 acho que pode ser assim:
`handleCloseModal` -> `onClose` ; `handleNewTab` -> `onConfirm`

O evento não precisa repetir o nome do componente.

2020-12-16 13:30 UTC, shiguemi32 commented on src/components/Tabs/Tabs.component.jsx
> +  handleRename: PropTypes.func.isRequired,
o onChange é o evento quando troca de aba

2020-12-16 13:31 UTC, shiguemi32 commented on src/components/Tabs/Tabs.component.jsx
> +    <DndProvider backend={HTML5Backend}>
Vou testar

2020-12-16 14:02 UTC, fberanizo commented on src/components/Tabs/Tabs.component.jsx
> +  handleRename: PropTypes.func.isRequired,
Aaah! Obrigado! :)

2020-12-16 17:50 UTC, cedric-matheus commented on src/components/Tabs/Tabs.component.jsx
> +    <DndProvider backend={HTML5Backend}>
> @shiguemi32 olhando o styleguide percebi que o `Tab` é conjunto de abas (antd TabPane) e `Tabs` é a barra com as abas + botão de nova aba + modal de nova aba.
> Estes nomes podem confundir um pouco. Eu mesmo, achei que o `Tab` era uma aba só.
> O que você acha de renomear `Tab` -> `Tabs` ; e `Tabs` -> `???`
> 
> ## --
> @shiguemi32 tem muitas properties no `Tabs.component.jsx` e elas são repassadas pro filhos `Tab` e `NewTabModal`. Tava pensando em dividir o DeploymentsTabsContainer.jsx em 2 containers: pro `DeploymentsTabContainer` e `NewTabModalContainer`
> 
> @SchafferCPqD e @cedric-matheus podem dar umas sugestões aqui para essa organização de container, por favor.

Acho legal a questão de renomear para ficar mais claro o que cada componente é, e também achei boa a ideia do Shiguemi de separar os containers, vai simplificar o código.

2020-12-19 20:25 UTC, fberanizo approved these changes

2020-12-19 20:52 UTC, merged