Component PropertiesPanel
platiagro/web-ui pull request #318
Opened 2020-12-23 18:25 UTC by shiguemi32

2020-12-23 19:56 UTC, cedric-matheus reviewed
Sugestões!

2020-12-23 19:56 UTC, cedric-matheus commented on src/components/PropertiesPanel/PropertiesPanel.component.jsx
> +      {resizableContent}
@shiguemi32 acho que vai ficar mais intuitivo se a gente utilizar o children aqui...

2020-12-23 19:56 UTC, cedric-matheus commented on src/containers/OperatorResizableSectionContainer/OperatorResizableSectionContainer.jsx
> +        style={{
@fberanizo @shiguemi32 @SchafferCPqD @schafferjrdev @miguelfferraz @samborba @hugooliv 

Pessoal, marquei todos vocês aqui para a gente tomar uma decisão coletiva sobre os estilos.

Vocês preferem tratar o estilo dentro dos componentes com JSS ou preferem adicionar os estilos em arquivos separados (.less)??

Alguns prós e contras que consigo identificar:

- Utilizar JSS:
  - Prós:
    - Todo o código do componente em um único lugar
    - Dispensa o uso de classes css

  - Contras:
    - Componentes podem ficar bem extensos

- Utilizar LESS:
  - Prós:
    - Cada tipo de arquivo com suas responsabilidades únicas
    - Componentes mais enxutos

  - Contras:
    - Necessário o uso de classes css

2020-12-23 20:18 UTC, fberanizo commented on src/containers/OperatorResizableSectionContainer/OperatorResizableSectionContainer.jsx
> +        style={{
Eu prefiro arquivos .less/.css.
Tenho uma duvida: a gente tem problema de hot-reloading pra arquivos .less?
Se isso não estiver funcionando, é bem mais chato usar o less no desenvolvimento.

2020-12-28 11:28 UTC, shiguemi32 commented on src/containers/OperatorResizableSectionContainer/OperatorResizableSectionContainer.jsx
> +        style={{
Testei aqui e não temos problema com  hot-reloading pra arquivos .less

2020-12-28 12:39 UTC, cedric-matheus reviewed
Observar os childrens.

2020-12-28 12:39 UTC, cedric-matheus commented on src/components/PropertiesPanel/PropertiesPanel.md
> +<PropertiesPanel children={children} tip={tip} title={title} />;
@shiguemi32 coloca o children como elemento filho... Acho que o nome pode ser resizableContent ou propertiesContent mesmo.

------
```js
<PropertiesPanel tip={tip} title={title}>
  {children / resizableContent / propertiesContent}
</PropertiesPanel>
```

2020-12-28 12:39 UTC, cedric-matheus commented on src/containers/OperatorResizableSectionContainer/OperatorResizableSectionContainer.jsx
> +      children={propertiesContent}
@shiguemi32 coloca o children como elemento filho...

------

```js
<PropertiesPanel tip={tip} title={title}>
  {propertiesContent}
</PropertiesPanel>
```

2020-12-28 20:21 UTC, fberanizo requested changes

2020-12-28 20:21 UTC, fberanizo commented on src/containers/OperatorResizableSectionContainer/OperatorResizableSectionContainer.jsx
> +        style={{
@shiguemi32 acho então que devemos trocar os `styles={{...}}` neste PR por uma classe CSS em um arquivo .less.

Tem neste arquivo e no arquivo `src/components/PropertiesPanel/PropertiesPanel.component.jsx`.

2020-12-30 11:31 UTC, fberanizo requested changes

2020-12-30 11:31 UTC, fberanizo commented on src/containers/OperatorResizableSectionContainer/OperatorResizableSectionContainer.jsx
> +        }}
@shiguemi32 acho que aqui também precisa mudar para uma classe CSS.

2020-12-30 11:31 UTC, fberanizo commented on src/containers/OperatorResizableSectionContainer/OperatorResizableSectionContainer.jsx
> +        }}
@shiguemi32 acho que aqui também precisa mudar para uma classe CSS.

2020-12-30 16:43 UTC, fberanizo approved these changes
👍

2020-12-30 16:44 UTC, merged