Feature - Rename deployment actions
platiagro/web-ui pull request #331
Opened 2021-01-11 21:33 UTC by cedric-matheus

- Create action types
- Create action
- Update reducer

2021-01-12 12:47 UTC, fberanizo requested changes

2021-01-12 12:47 UTC, fberanizo commented on src/store/deployments/actions.js
> +}
@cedric-matheus acho que aqui precisa fazer uma lógica pra quando é renomeado para um nome que já existe. +- como esse:
https://github.com/platiagro/web-ui/blob/7dcebfcb8e5e4fbe04bfeb2e3b79b3bcedd96f67/src/store/experiments/actions.js#L158-L163

2021-01-14 16:09 UTC, cedric-matheus commented on src/store/deployments/actions.js
> +}
Opa!

Vou fazer... eu estava validando apenas no componente... mas vou validar na action tbm...

2021-01-14 16:10 UTC, cedric-matheus commented on src/store/deployments/actions.js
> +}
Beleza :+1:

2021-01-19 12:34 UTC, fberanizo approved these changes

2021-01-19 12:34 UTC, merged