Added actions to show and hide prepare modal
platiagro/web-ui pull request #353
Opened 2021-01-27 13:52 UTC by schafferjrdev

Added actions showPrepareDeploymentsModal and hidePrepareDeploymentsModal to manage PrepareDeployments Modal, but no onConfirm action was added yet.

2021-01-27 18:06 UTC, fberanizo requested changes
Olá, @SchafferCPqD .
Tem algumas alterações que sugeri para já finalizar a funcionalidade de `PrepareDeployments`.
Não estavam descritas no Jira, porém da forma que ficou não é mais possível implantar um experimento.
Seria importante dar merge em uma versão que continue acionando o service/backend.
Você pode, por favor, dar uma força com esses ajustes?

2021-01-27 18:06 UTC, fberanizo commented on src/store/deployments/actions.js
> +  /*
@SchafferCPqD neste método tbm mudaria de `experimentId` para `experiments` (a lista dos checkboxes selecionados).

A chamada do service para fazer o "prepareDeployments" é este que já está no código comentado: P `createDeployment(experiments)`.

Você pode alterar para continuar acionando o serviço, por favor?

2021-01-27 18:57 UTC, schafferjrdev commented
Certo, posso alterar sim, eu tinha achado que essas modificações para o Prepare Deployments estaria em outra tarefa, pois não estavam mencionadas lá. Então o objetivo real é tornar o prepare deployments completamente funcional, certo?

2021-01-27 20:10 UTC, fberanizo commented
> Certo, posso alterar sim, eu tinha achado que essas modificações para o Prepare Deployments estaria em outra tarefa, pois não estavam mencionadas lá. Então o objetivo real é tornar o prepare deployments completamente funcional, certo?

Oi, acho melhor tentar fazer isso já pq não outra tarefa relacionada a isso nessa sprint.

2021-02-04 17:52 UTC, schafferjrdev commented
O modal de preparar implantação agora deve ter todas as funcionalidades necessárias!

2021-02-08 16:21 UTC, fberanizo approved these changes

2021-02-08 16:21 UTC, merged