Fix - Operator parameters
platiagro/web-ui pull request #357
Opened 2021-02-04 01:08 UTC by cedric-matheus

- Configure operator on connection

2021-02-04 12:19 UTC, fberanizo requested changes
@cedric-matheus testei e está ok, porém acho que podemos evitar a request a mais. Analise, por favor, essa mudança.

2021-02-04 12:19 UTC, fberanizo commented on src/store/operators/actions.js
> +  }
@cedric-matheus acho que seria bom evitar essa request a mais. Dá pra buscar o valor do state?

2021-02-04 13:44 UTC, cedric-matheus commented on src/store/operators/actions.js
> +  }
Acho que conseguimos sim, vou analisar aqui. :)

2021-03-02 17:17 UTC, fberanizo approved these changes

2021-03-02 17:17 UTC, merged