Feature - Create deployment
platiagro/web-ui pull request #373
Opened 2021-03-22 20:48 UTC by cedric-matheus

- Rectify container name
- Show new deployment modal
- Remove bug from experiments store
- Get experiments on mount
- Render component on experimentsData change
- Get templates on mount
- Render component on templatesData change
- Rectify renderUser bug
- Add loading to modal
- Create new deployment modal loading state
- Add new deployment modal loading and hide
- Add loading state to modal container

2021-03-23 12:45 UTC, fberanizo requested changes
Uma comportamento que notei só agora é que pra selecionar um item da tabela abaixo precisa clicar diretamente no input-radio. O ideal seria permitir o click em qualquer parte da linha. 
Pode fazer essa alteração, por favor?
![image](https://user-images.githubusercontent.com/1791381/112147892-fa55bc00-8bbb-11eb-951a-e32288e3a456.png)

2021-03-23 12:45 UTC, fberanizo commented on src/containers/NewDeploymentModalContainer/NewDeploymentModalContainer.jsx
> +  }, [fetchExperiments, fetchTemplates, projectId]);
@cedric-matheus eu escrevi e apaguei algumas vezes que quero falar aqui...mas não sei como explicar direito. vou tentar mesmo assim:
me parece meio esquisito passar uma prop `fetch....` pra um componente. Sei lá...na minha cabeça props de um component geralmente são valores (`visible`, `experiments`, ...) ou eventos (`onConfirm`, `onLoad`, ...). Achei que ficou esquisito.
Talvez pudesse fazer esses `fetch...` no Container...não sei...o que você acha?

2021-03-23 13:53 UTC, LuanEdCosta commented on src/store/ui/actions.js
> +    type: actionTypes.DEPLOYMENT_MODAL_START_LOADING,
Aqui não deveria ser o type `actionTypes.DEPLOYMENT_MODAL_END_LOADING`?

2021-03-23 17:33 UTC, cedric-matheus commented on src/store/ui/actions.js
> +    type: actionTypes.DEPLOYMENT_MODAL_START_LOADING,
Valew :)

Corrigido!

2021-03-23 17:33 UTC, cedric-matheus commented on src/containers/NewDeploymentModalContainer/NewDeploymentModalContainer.jsx
> +  }, [fetchExperiments, fetchTemplates, projectId]);
Valew :)

- Feature de seleção por clique na linha implementada;
- Container refatorado.

2021-03-24 12:32 UTC, fberanizo requested changes
@cedric-matheus achei algumas coisas que podem ser melhoradas:

Ao confirmar o modal sem selecionar o valor aparece este popup. Podemos: 
Tratar essa mensagem, exibindo "Selecione um experimento ou fluxo de tarefas".
e desabilitar o botão enquanto não há valor selecionado.
![image](https://user-images.githubusercontent.com/1791381/112309739-7581a580-8c82-11eb-9788-af23370a7409.png)

---

Vi que você ajustou pra deixar toda a linha clicável.. Ficou legal. :) Sugiro ainda adicionar um `cursor: pointer;` no css da linha, pra indicar que ela é clicável.

---

Atualizei a máquina .44 com a versão deste PR. As vezes o ambiente fica um pouco lento, aí aconteceu o seguinte comigo: 
Cliquei em `Escolher fluxo` antes de terminar o load da tela de detalhes de projeto.
O modal deu umas piscadas, as vezes 1 vez, em outras fica preso num loop reabrindo várias vezes. Pode ter a ver com os `fetch...` no `NewDeploymentModalContainer`, não tenho certeza. :/ Tenta reproduzir, por favor.

2021-03-25 18:17 UTC, cedric-matheus commented
> @cedric-matheus achei algumas coisas que podem ser melhoradas:
> 
> Ao confirmar o modal sem selecionar o valor aparece este popup. Podemos:
> Tratar essa mensagem, exibindo "Selecione um experimento ou fluxo de tarefas".
> e desabilitar o botão enquanto não há valor selecionado.
> ![image](https://user-images.githubusercontent.com/1791381/112309739-7581a580-8c82-11eb-9788-af23370a7409.png)
> 
> Vi que você ajustou pra deixar toda a linha clicável.. Ficou legal. :) Sugiro ainda adicionar um `cursor: pointer;` no css da linha, pra indicar que ela é clicável.
> 
> Atualizei a máquina .44 com a versão deste PR. As vezes o ambiente fica um pouco lento, aí aconteceu o seguinte comigo:
> Cliquei em `Escolher fluxo` antes de terminar o load da tela de detalhes de projeto.
> O modal deu umas piscadas, as vezes 1 vez, em outras fica preso num loop reabrindo várias vezes. Pode ter a ver com os `fetch...` no `NewDeploymentModalContainer`, não tenho certeza. :/ Tenta reproduzir, por favor.

Alterações realizadas :)

2021-03-26 12:04 UTC, fberanizo approved these changes

2021-03-26 12:04 UTC, merged