Fix Components Position
platiagro/web-ui pull request #391
Opened 2021-04-07 16:05 UTC by LuanEdCosta

Some components were in the wrong place. This PR fix this error by putting them into the `components` and adding the style guide for the ones that didn't have.

2021-04-07 19:19 UTC, LuanEdCosta commented
Este PR altera muitos arquivos porque é uma refatoração. 
Para corrigir os `code smells` tive que mexer no componente TaskBox. Quando testei me parece estar tudo certo, mas queria pedir para quem for revisar o código para dar uma lida com mais atenção neste componente que agora fica em `components/TaskBox`. :rocket:

2021-04-09 13:03 UTC, schafferjrdev commented on src/components/Buttons/RemoveOperatorButton/RemoveOperatorButton.md
> +**Loading**
Pode indicar aqui que é Disabled?

2021-04-09 13:05 UTC, schafferjrdev commented on src/components/ToolbarConfig/ToolbarConfig.md
> +**With Operator and Delete Button**
Aqui na verdade é Fit Button e Delete Button

2021-04-09 13:22 UTC, schafferjrdev requested changes
Está tudo legal, só aqueles dois comentários que fiz

2021-04-09 17:04 UTC, schafferjrdev approved these changes
LGTM!

2021-04-09 17:04 UTC, merged