Fix - Deployment Page Responsiveness
platiagro/web-ui pull request #412
Opened 2021-05-03 16:51 UTC by LuanEdCosta

- Adjust monitoring panel toolbar for small screens or when reduces the window width
- Logs panel don't influences the PropertiesPanel width anymore
- Reduce the FlowDrop min height to allow the panels grow and prevent the page scroll to appear
- Create custom hook in MonitoringPanelContainer to show just one panel per time, so both monitorings panel and the logs panel cannot be shown at the same time

2021-05-03 17:39 UTC, fberanizo approved these changes
Visualmente tá bem melhor aqui :)

![image](https://user-images.githubusercontent.com/1791381/116911486-51b86480-ac1d-11eb-83b3-96c47c69091c.png)
![image](https://user-images.githubusercontent.com/1791381/116911514-5a109f80-ac1d-11eb-8a5c-a6d99a66e331.png)

2021-05-03 17:43 UTC, fberanizo commented
@LuanEdCosta senti falta de mudar o cursor ao passá-lo sobre a caixinha de monitoramento. Me parece importante pra mostrar que ele é clicável (e faz aparecer botões de "Excluir" e "Ver monitoramento"

2021-05-03 17:46 UTC, LuanEdCosta commented
Verdade, o cursor não fica como "pointer" no hover. Vou alterar aqui e já subo

2021-05-04 12:21 UTC, fberanizo requested changes
@LuanEdCosta conforme conversamos, o botão de logs fica "escondido" atrás do painel de logs depois que eu abro:
![image](https://user-images.githubusercontent.com/1791381/117002890-862e2e00-acba-11eb-8202-936aade14dca.png)

2021-05-04 16:09 UTC, fberanizo approved these changes
Tudo certo agora! :)
![image](https://user-images.githubusercontent.com/1791381/117034658-ea141f00-acd9-11eb-8c07-f2b6ad373a44.png)

2021-05-04 16:10 UTC, merged