Fix - Deployments Page State Bugs
platiagro/web-ui pull request #418
Opened 2021-05-05 16:44 UTC by LuanEdCosta

- Clear the operators list when delete the last deployment
- Clear the monitorings list when delete the last deployment
- Deselect operator when delete the last deployment
- Deselect operator when change the selected tab
- Delete `src/store/projectDeployments` because this store is not used in any other place and their action types generate bugs with the `src/store/deployments` store when using the same action type value
- Add prefix in some action types to prevent future bugs
- The monitoring panel is hidden by default when the user opens the deployments page
- Clear deployments when leave the deployments page
- Close the logs panel when it get unmounted

2021-05-06 16:55 UTC, fberanizo requested changes

2021-05-06 16:55 UTC, fberanizo commented on src/containers/DeploymentsTabsContainer/DeploymentsTabsContainer.jsx
> +        dispatch(clearAllDeploymentOperators());
@LuanEdCosta notei que as caixinhas e monitoramentos são limpos, mas os logs continuam em exibição:
possivelmente também acontece isso no experimento
![image](https://user-images.githubusercontent.com/1791381/117336425-90932800-ae72-11eb-9f8a-3f9ff188fc56.png)

2021-05-07 16:04 UTC, LuanEdCosta commented
@fberanizo Para poder fazer a lista de logs ser limpada quando seleciona um outro experimento e limpar quando exclui um experimento eu preciso esperar o PR do @cedric-matheus https://github.com/platiagro/web-ui/pull/419

Esse PR dele mexe tanto no ExperimentTabs quanto em `store/experiments/actions.js` os dois arquivos que eu possivelmente mexeria para fazer essa limpeza de estado.

2021-05-13 16:49 UTC, fberanizo approved these changes
Funcionalmente parece ok.
![image](https://user-images.githubusercontent.com/1791381/118158317-fee76580-b3f1-11eb-811b-a0cee3da9639.png)

2021-05-13 16:50 UTC, fberanizo commented
@schafferjrdev há alterações em store de deployments neste PR. Veja se pode dar conflito com as coisas que você está fazendo.

2021-05-13 17:07 UTC, schafferjrdev reviewed
Ok

2021-05-13 17:26 UTC, fberanizo approved these changes

2021-05-13 17:26 UTC, merged