Feature - Create the NewTask and TaskDetails Page
platiagro/web-ui pull request #440
Opened 2021-05-28 21:29 UTC by LuanEdCosta

- Create the NewTask page that helps the user to find a task template to create
- Create the TaskDetails page with these functionalities: 
  - Edit a task when loose focus on input fields or selects 
  - Upload deployment and experiment jupyter notebooks
  - Share the task via e-mail or publish in marketplace
  - Delete the task
  - Edit the task name
  - Edit docket image, arguments and commands

2021-05-28 21:32 UTC, LuanEdCosta commented
Para testar a nova página acesse `localhost:3000/nova-tarefa`, porque ela ainda não foi adicionada em `src/pages/Tasks`

2021-05-31 14:01 UTC, fberanizo requested changes
@LuanEdCosta a maior parte das revisões é relacionada a padrões. Deixa a sua opinião, por favor.

2021-05-31 14:23 UTC, LuanEdCosta commented on src/pages/NewTask/NewTaskDefaultTemplates.jsx
> +  handleCreateDockerTask,
Já estou acostumado a colocar o `handle` no começo de todas as funções dentro de um componente, mas tanto faz para mim. A maioria dos arquivos seguem esse padrão também, me lembro de poucos lugares que usavam o `on`. Concordo que temos que seguir um padrão, então podemos ver com o resto do time o que eles preferem.

Arquivos que usam `const on...` 
![image](https://user-images.githubusercontent.com/36794274/120207122-6b3fd280-c202-11eb-8142-0d352e9de1e8.png)

Arquivos que usam `const handle...`
![image](https://user-images.githubusercontent.com/36794274/120207157-75fa6780-c202-11eb-90a3-3a8a4b51cf1f.png)

2021-05-31 14:24 UTC, LuanEdCosta commented on src/store/tasks/tasks.actions.js
>      );
Ah sim, eu preciso remover isso quando integrar na página que tem a tabela de tarefas, assim como remover aquelas actions que abrem o modal de adicionar/editar tarefa. Acho que posso adicionar um TODO nessas linhas :thinking:.

2021-05-31 14:24 UTC, LuanEdCosta commented on src/store/tasks/tasks.actions.js
> +export const addTask = (task, successCallback) => async (dispatch) => {
Podemos sim. Vou alterar.

2021-05-31 14:24 UTC, LuanEdCosta commented on src/utils.js
> +};
Nesse caso estou criando uma Promise justamente pra usar async/await quando for utilizar essa função. Não dá pra usar async/await com o FileReader porque ele trabalha apenas com as funções `onload` e `onerror` que são callbacks.

2021-05-31 14:25 UTC, LuanEdCosta commented on src/services/TasksApi.js
> +  return taskApi.put(`/tasks/mail/${uuid}`, { email });
Ah legal, vou alterar isso :+1:

2021-05-31 14:25 UTC, LuanEdCosta commented on src/routes/Main.routes.jsx
> +      <Route path='/tarefa/:taskId' component={TaskDetails} />
Verdade, vou alterar.

2021-05-31 14:25 UTC, LuanEdCosta commented on src/pages/TaskDetails/TaskDetailsInfoFooter.jsx
> +      </div>
Ah não tinha lembrado desse componente. Vou tentar reutilizar :+1:.

2021-05-31 14:25 UTC, LuanEdCosta commented on src/configs/TaskCategories.js
> +  },
Acho que entendi, então ele não aparece na tela `/nova-tarefa` e nem na categoria dos detalhes da tarefa?

2021-05-31 14:26 UTC, LuanEdCosta commented on src/pages/TaskDetails/TaskDetailsHeader.jsx
> +                placeholder='Escreva um nome para a tarefa'
Ah sim, eu até pensei em fazer com modal também na hora que procurei se já existia um título editável, mas segui o design. Vou tentar aumentar a largura do input ou diminuo o placeholder :+1:.
![image](https://user-images.githubusercontent.com/36794274/120206918-27e56400-c202-11eb-81db-f7fe51bd5c29.png)

2021-05-31 15:06 UTC, fberanizo commented on src/configs/TaskCategories.js
> +  },
Isso mesmo. Não aparece na tela de nova tarefas e na lista de categorias.

2021-06-01 00:34 UTC, fberanizo requested changes
@LuanEdCosta me esqueci de falar no PR anterior, um comportamento que não está muito legal é o do trigger de atualização.

Quando eu edito o campo e não altero valor algum ainda assim acontecer a requisição e aparece o popup de sucesso.
Dá pra verificar se houve mudanças  e só fazer a requisição neste caso?
(acho que é assim que funciona lá no painel de parâmetros do operator).

2021-06-01 12:16 UTC, LuanEdCosta commented
Pode deixar. Vou fazer isso ainda hoje.

2021-06-02 14:32 UTC, fberanizo approved these changes
@LuanEdCosta acho tem mais alguns ajustes de comportamento a fazer (ex: quando mostrar o painel Docker), mas vou aprovar e fazemos assim que a API do backend estiver OK. :)

2021-06-02 14:33 UTC, merged