Feature/operators store refactor
platiagro/web-ui pull request #443
Opened 2021-06-01 12:58 UTC by schafferjrdev

Move all data from deploymentOperator/Operators store to operator/Operators store.

Change operators store to new pattern.

2021-06-01 18:45 UTC, fberanizo approved these changes
👍

2021-06-01 19:37 UTC, LuanEdCosta requested changes
Achei um BUG aqui que acredito não ter a ver com este PR, mas tem muita relação, então talvez dê pra corrigir nele mesmo. @fberanizo Você acha que pode ser nesse PR ou abrimos outra tarefa?

---

**BUG: Operators da tela de experimentação permanecem ao entrar na tela de pré-implantação**

**Como reproduzir:**
1 - Escolha um projeto que não tenha nenhum fluxo em pré-implantação ou faça ele não ter nenhum
2 - Crie um experimento e adicione um ou mais Operators
3 - Clique no botão voltar do header da página (logo a esquerda do título)
4 - Entre na tela de pré-implantação
5 - Você verá os operators do experimento que você estava vendo anteriormente

**Possível Causa:**
O array de operators não é limpado quando a página de experimentação é desmontada

**Possível Solução:**
Criar action para limpar o array de operators de experimento e usá-lo no retorno de um useEffect na tela de experimentação, para limpar o estado ao desmontar a página.

2021-06-01 19:59 UTC, LuanEdCosta requested changes
Nos arquivos `src/store/operator/operator.actions.js` e `src/store/operators/operators.actions.js` existem JsDoc duplicados e faltam neles o tipo e o comentário. Se não tiver tipo ou comentário um warning aparecerá no terminal quando executar o projeto.

Imagem Ilustrativa:
![image](https://user-images.githubusercontent.com/36794274/120381379-bb995c00-c2f8-11eb-8f08-a28042fa92d9.png)
 
---

Ainda existem algumas coisas a serem feitas para padronizar totalmente essas stores para o novo formato, como:

- Não usar mais o `message` diretamente do `antd` em `src/store/operators/operators.actions.js`
- Substituir as actions de loading de `store/ui` pelo `addLoading` e `removeLoading` de `store/loading` 
- Criar os selectors em um arquivo `[storeName].selectors.js`

Mas é possível finalizar a padronização para o novo formado posteriormente em outra tarefa. O que acha @fberanizo?

2021-06-01 19:59 UTC, LuanEdCosta requested changes
...

2021-06-01 20:34 UTC, fberanizo commented
> Achei um BUG aqui que acredito não ter a ver com este PR, mas tem muita relação, então talvez dê pra corrigir nele mesmo. @fberanizo Você acha que pode ser nesse PR ou abrimos outra tarefa?
> 
> **BUG: Operators da tela de experimentação permanecem ao entrar na tela de pré-implantação**
> 
> **Como reproduzir:**
> 1 - Escolha um projeto que não tenha nenhum fluxo em pré-implantação ou faça ele não ter nenhum
> 2 - Crie um experimento e adicione um ou mais Operators
> 3 - Clique no botão voltar do header da página (logo a esquerda do título)
> 4 - Entre na tela de pré-implantação
> 5 - Você verá os operators do experimento que você estava vendo anteriormente
> 
> **Possível Causa:**
> O array de operators não é limpado quando a página de experimentação é desmontada
> 
> **Possível Solução:**
> Criar action para limpar o array de operators de experimento e usá-lo no retorno de um useEffect na tela de experimentação, para limpar o estado ao desmontar a página.

Oi! Melhor abrirmos Jira e outro PR pra este bug, :)

2021-06-01 20:35 UTC, fberanizo commented
> Nos arquivos `src/store/operator/operator.actions.js` e `src/store/operators/operators.actions.js` existem JsDoc duplicados e faltam neles o tipo e o comentário. Se não tiver tipo ou comentário um warning aparecerá no terminal quando executar o projeto.
> 
> Imagem Ilustrativa:
> ![image](https://user-images.githubusercontent.com/36794274/120381379-bb995c00-c2f8-11eb-8f08-a28042fa92d9.png)
> 
> Ainda existem algumas coisas a serem feitas para padronizar totalmente essas stores para o novo formato, como:
> 
> * Não usar mais o `message` diretamente do `antd` em `src/store/operators/operators.actions.js`
> * Substituir as actions de loading de `store/ui` pelo `addLoading` e `removeLoading` de `store/loading`
> * Criar os selectors em um arquivo `[storeName].selectors.js`
> 
> Mas é possível finalizar a padronização para o novo formado posteriormente em outra tarefa. O que acha @fberanizo?

@schafferjrdev me parecem coisas rápidas. Pode fazer essas alterações neste PR mesmo, por favor?
Depois disso eu já fecho a tarefa.

2021-06-08 12:45 UTC, fberanizo approved these changes
Testado com sucesso no amb. .44.

@LuanEdCosta  e @cedric-matheus acho importante que vocês façam rebase/merge dessas mudanças.

2021-06-08 12:45 UTC, merged