Feature - Task Pages Integration
platiagro/web-ui pull request #452
Opened 2021-06-10 17:34 UTC by LuanEdCosta

- Integrate the NewTask and TaskDetails page with the Tasks page. Now the button to add a new task open the NewTask, the TaskDetails page is opened when click in the task, but the button to delete and copy the task is working in the same way as before.
- Create a explanation for Jupyter Notebooks in the NotebooksExplanationModal component.
- Disable Marketplace button in the NewTaskMarketplacePanel component, add a tooltip to explain that the marketplace is coming soon and change the title for the same reason.
-  Add tooltip in the publish in marketplace button inside the ShareTaskModal to explain that the marketplace will be available as soon as possible.
- Delete the old code that won't be necessary anymore, including the modals to edit and create a task

2021-06-10 17:37 UTC, LuanEdCosta commented
@fberanizo Libero este PR para a revisão assim que as novas funcionalidades forem desenvolvidas no back-end. :+1:

2021-06-10 17:45 UTC, LuanEdCosta commented
Enquanto não temos o marketplace, as partes do sistema relacionadas a ele ficarão desabilitadas. É importante deixarmos claro para o usuário que em breve a funcionalidade estrá disponível:

![image](https://user-images.githubusercontent.com/36794274/121572245-56312380-c9fa-11eb-86e4-04e0c91ded32.png)

2021-06-30 16:44 UTC, fberanizo requested changes
@LuanEdCosta além dos ícones, também tem este popover, que pode ser removido:
![image](https://user-images.githubusercontent.com/1791381/123999060-7b390680-d9a8-11eb-8301-7b2f26d4fa38.png)

---
Ao criar uma tarefa "Docker" parece que o request não mandou informações (para que o backend saiba que é tarefa docker).

Além do `category:"DEFAULT"`, precisa passar um "image":"docker.io/busybox:latest" (talvez um `"commands": ["echo", "Hello World"]`

2021-06-30 16:44 UTC, fberanizo commented on src/pages/Tasks/TasksTable/index.js
>                />
@LuanEdCosta como ainda não temos o Marketplace (e compartilhamento por usuario), pode remover estes 2 ícones, por favor.

2021-06-30 19:13 UTC, LuanEdCosta commented
Estava testando aqui e percebi que `commands` e `arguments` são arrays mas eu fiz como strings na tela. @fberanizo Vou trocar estes dois campos para aquele select com tags, porque ele manipula um array internamente e facilita a digitação do usuário. Assim que eu subir os commits disso a tarefa estará finalizada.

2021-06-30 20:53 UTC, fberanizo reviewed
@LuanEdCosta deu pra ver agora a tela do docker :)

Só um detalhe, parece que os links estão com o hostname como base da URL:
![image](https://user-images.githubusercontent.com/1791381/124029831-f06a0300-d9cb-11eb-9721-c7fcd114904a.png)

2021-06-30 21:01 UTC, fberanizo commented
> Estava testando aqui e percebi que `commands` e `arguments` são arrays mas eu fiz como strings na tela. @fberanizo Vou trocar estes dois campos para aquele select com tags, porque ele manipula um array internamente e facilita a digitação do usuário. Assim que eu subir os commits disso a tarefa estará finalizada.

Esses campos eu não sei muito bem como seria o melhor elemento de tela
Eles são o ENTRPOINT e o CMD de um Dockerfile. 

Tem ferramentas da AWS (AWS Batch) que deixa as pessoas digitarem em um TextArea e fazem o split depois 
![image](https://user-images.githubusercontent.com/1791381/124030529-a5042480-d9cc-11eb-8cd0-d942ec34b3c1.png)

Ou faz a pessoa digitar em formato JSON.
![image](https://user-images.githubusercontent.com/1791381/124030675-cbc25b00-d9cc-11eb-967f-1f0ef6fcaed3.png)

O Input Array (tipo o do tags) acho que pode dar problemas com o exemplo da imagem `echo 'hello world'`, em que o `'` inicia um item do array e o texto tem espaço. 

## O que você acha de deixar a pessoa digitar JSON (e fazer uma validação)?

2021-07-01 13:50 UTC, LuanEdCosta commented
@fberanizo  Achei legal a ideia de escrever em JSON. Vamos fazer assim então:
- Neste PR faço um split nos espaços em branco pra transformar em array
- Abrimos uma nova tarefa para permitir a escrita em JSON e em formato bash igual as imagens que você mostrou, porque ficou bem legal para o usuário. Tem também que mostrar a conversão para JSON, assim fica bem fácil.

2021-07-01 14:08 UTC, LuanEdCosta commented
@fberanizo Agora finalmente acredito que podemos dar merge nesse PR :+1:

2021-07-01 14:23 UTC, LuanEdCosta commented
> SonarCloud Quality Gate failed.
> 
> [<img alt="Bug" width="16" height="16" src="https://camo.githubusercontent.com/deaad8c9d9b09977da3f9aa455689440a17356bb359560328463022a0d9d1362/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=BUG) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=BUG)
> [<img alt="Vulnerability" width="16" height="16" src="https://camo.githubusercontent.com/60273222b26453a76e9c369287fa0106b151cbaae4fa4ce00e149b269a0fac67/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=VULNERABILITY) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=VULNERABILITY)
> [<img alt="Security Hotspot" width="16" height="16" src="https://camo.githubusercontent.com/a0723b4c04ec36cc8d010cca748afdc6300592f020130edca7403ea5b17ffe35/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742e706e67">](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=452&resolved=false&types=SECURITY_HOTSPOT) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=452&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=452&resolved=false&types=SECURITY_HOTSPOT)
> [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=CODE_SMELL) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=CODE_SMELL) [2 Code Smells](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=452&resolved=false&types=CODE_SMELL)
> 
> [<img alt="0.0%" width="16" height="16" src="https://camo.githubusercontent.com/6c4a9474d282d89b0f89980e1deba92e8852fccb4933755a65493099ed25f18e/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302e706e67">](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=452&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=452&metric=new_coverage&view=list)
> [<img alt="0.8%" width="16" height="16" src="https://camo.githubusercontent.com/17c8580971832aaa80226d5b1c5c61cc2f9ef6a863fc6f6bae0ab2c7d45165ed/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332e706e67">](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=452&metric=new_duplicated_lines_density&view=list) [0.8% Duplication](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=452&metric=new_duplicated_lines_density&view=list)

O code smell do retorno de função vai ser corrigido no PR que transformarmos em JSON. :smile:

2021-07-01 14:25 UTC, merged