Create container to upload deployment dataset
platiagro/web-ui pull request #458
Opened 2021-06-21 14:12 UTC by schafferjrdev

Create container to upload deployment dataset

2021-06-21 20:09 UTC, fberanizo requested changes
@schafferjrdev você pode, por favor, aproveitar para substituir os textos da parte da aplicação externa:

"Você pode testar o fluxo com um cliente HTTP, por exemplo o [Postman](https://www.postman.com/downloads/)."
![image](https://user-images.githubusercontent.com/1791381/122818731-efd8ba80-d2af-11eb-87b6-1ce6ecd6f774.png)

---

Modal: "Saiba mais"

Quando você implanta seu fluxo, a PlatIAgro cria um Serviço REST do [Seldon Core](https://docs.seldon.io/projects/seldon-core/en/stable/index.html).
Para testar o serviço, siga os seguintes passos:

1. [BOTÃO]
2. Escolha o método POST.
3. Preencha o Header Content-Type: application/json
4. Preencha o corpo da requisição:

{
    "data": {
        "ndarray": [
            [...]
        ]
    }
}
Envie a requisição. Em caso de sucesso, o corpo da resposta terá o mesmo formato do corpo da requisição.
Consulte a [documentação do Seldon Core](https://docs.seldon.io/projects/seldon-core/en/stable/workflow/github-readme.html#send-api-requests-to-your-deployed-model) para mais detalhes.

![image](https://user-images.githubusercontent.com/1791381/122821247-fa488380-d2b2-11eb-90e5-2e1a36434659.png)

2021-06-22 12:45 UTC, schafferjrdev commented on src/containers/DeploymentDatasetUploadContainer/DeploymentDatasetUploadContainer.jsx
> +  // TODO: Criar seletores
Pelo menos fora da função com o hook novo

2021-06-22 22:31 UTC, fberanizo requested changes
@schafferjrdev coloquei essa versão lá no amb. 44 Está okay agora o load do dataset
Notei só um comportamento indesejável. O botão "Testar Fluxo" ficou desabiltado quando importei um arquivo. (se eu sair e voltar pra pré-implantação ele fica habilitado novamente).

![image](https://user-images.githubusercontent.com/1791381/123007504-ae1f4100-d38f-11eb-9eac-c3e4e49cf6a8.png)


Provavelmente é algo no selector. Pode modificar, por favor para que o botão fique habilitado?
https://github.com/platiagro/web-ui/blob/8d27b57a53ac041ba2e44cfc442a3d98402e1448/src/containers/DeploymentToolbarContainer/DeploymentToolbarContainer.jsx#L30-L40

2021-06-25 16:15 UTC, fberanizo approved these changes
👍 testado com sucesso no amb .120

2021-06-25 16:21 UTC, merged