Fix/UI store loading actions
platiagro/web-ui pull request #459
Opened 2021-06-22 16:10 UTC by LuanEdCosta

- Remove loading action types, actions and reducer cases from the ui store
- Remove useless comments from the ui store
- Using addLoading and removeLoading with the request action type to store the loading state
- Use the useLoading hook to retrieve the loading state in React components

Some loading states have not been removed to avoid bugs and because they are used in complex logic that can be refactored along with the experimentRuns store. These loading states are:

- EXPERIMENT_TRAINING_LOADING_DATA
- EXPERIMENT_TRAINING_DATA_LOADED
- EXPERIMENT_DELETE_TRAINING_LOADING_DATA
- EXPERIMENT_DELETE_TRAINING_DATA_LOADED

2021-06-22 16:21 UTC, LuanEdCosta commented
Como o PR https://github.com/platiagro/web-ui/pull/456 do @cedric-matheus refatora a store de templates e também remove um state de loading, é melhor esperarmos o merge dele para que eu possa finalizar este daqui.

Para evitar mais conflitos eu não mexi nestes estados de loading que são usados em `store/templates`:

- TASKS_MENU_LOADING_DATA
- TASKS_MENU_DATA_LOADED
- TEMPLATE_LOADING_DATA
- TEMPLATE_DATA_LOADED
- EXPERIMENT_OPERATORS_LOADING_DATA
- EXPERIMENT_OPERATORS_DATA_LOADED

2021-06-22 22:43 UTC, fberanizo commented
> Como o PR #456 do @cedric-matheus refatora a store de templates e também remove um state de loading, é melhor esperarmos o merge dele para que eu possa finalizar este daqui.
> 
> Para evitar mais conflitos eu não mexi nestes estados de loading que são usados em `store/templates`:
> 
> * TASKS_MENU_LOADING_DATA
> * TASKS_MENU_DATA_LOADED
> * TEMPLATE_LOADING_DATA
> * TEMPLATE_DATA_LOADED
> * EXPERIMENT_OPERATORS_LOADING_DATA
> * EXPERIMENT_OPERATORS_DATA_LOADED

@LuanEdCosta fiz o merge. Veja os conflitos gerados, por favor :)

2021-06-23 14:52 UTC, LuanEdCosta commented
@fberanizo Conflitos resolvidos e já finalizei o que precisava nessa tarefa :+1:

2021-06-25 16:31 UTC, fberanizo commented
@LuanEdCosta você pode, por favor, dar rebase (ou merge) das alterações que foram pra master hoje.

Quero testar pra ver se o merge não vai perder alguma coisa que foi desenvolvida pelo Schaffer (no container de upload de arquivo/dataset)

2021-06-28 14:27 UTC, fberanizo requested changes
@LuanEdCosta este PR deu alguns erros no build após o merge:
https://github.com/platiagro/web-ui/pull/459/checks?check_run_id=2932155704

Verifica, por favor.

2021-06-29 19:29 UTC, fberanizo commented
> SonarCloud Quality Gate failed.
> 
> [<img alt="Bug" width="16" height="16" src="https://camo.githubusercontent.com/deaad8c9d9b09977da3f9aa455689440a17356bb359560328463022a0d9d1362/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=BUG) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=BUG)
> [<img alt="Vulnerability" width="16" height="16" src="https://camo.githubusercontent.com/60273222b26453a76e9c369287fa0106b151cbaae4fa4ce00e149b269a0fac67/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=VULNERABILITY) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=VULNERABILITY)
> [<img alt="Security Hotspot" width="16" height="16" src="https://camo.githubusercontent.com/a0723b4c04ec36cc8d010cca748afdc6300592f020130edca7403ea5b17ffe35/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742e706e67">](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=459&resolved=false&types=SECURITY_HOTSPOT) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=459&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=459&resolved=false&types=SECURITY_HOTSPOT)
> [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=CODE_SMELL) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=459&resolved=false&types=CODE_SMELL)
> 
> [<img alt="0.0%" width="16" height="16" src="https://camo.githubusercontent.com/6c4a9474d282d89b0f89980e1deba92e8852fccb4933755a65493099ed25f18e/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302e706e67">](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=459&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=459&metric=new_coverage&view=list)
> [<img alt="0.0%" width="16" height="16" src="https://camo.githubusercontent.com/17c8580971832aaa80226d5b1c5c61cc2f9ef6a863fc6f6bae0ab2c7d45165ed/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332e706e67">](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=459&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=459&metric=new_duplicated_lines_density&view=list)

@LuanEdCosta o merge quebrou de novo este PR🤦‍♂️
pode manter o foco lá nos bugs, por enquanto. Depois voltamos pra este PR :/

2021-07-07 17:10 UTC, fberanizo approved these changes

2021-07-07 17:10 UTC, merged