Feature/single parameter edition
platiagro/web-ui pull request #498
Opened 2021-07-26 17:22 UTC by cedric-matheus

- Create update operator parameter service
- Create update operator parameter action type
- Create update operator parameter action
- Update container to use new update operator parameter action

2021-07-27 13:06 UTC, fberanizo requested changes
@cedric-matheus parece que depois da alteração o polling está interferindo com a exibição de itens do painel. Provavelmente algum re-render que não existia antes. Neste caso pode causar um problema de usabilidade (vídeo abaixo) em que um select é fechado sozinho, sem clicar na tela.

Acho que isso precisamos ajustar :x

https://user-images.githubusercontent.com/1791381/127158301-6ea8301a-f97a-4a03-9733-79b94c606a5c.mp4

2021-07-27 13:23 UTC, cedric-matheus commented on src/store/operator/operator.actions.js
> +      });
É verdade... vou ajustar!

2021-07-27 14:20 UTC, LuanEdCosta reviewed
@cedric-matheus Para tentar corrigir estes re-renders você pode tentar utilizar o hook `useDeepSelector`, que faz comparação profunda e não gera novas renderizações se os dados realmente não foram alterados. O useSelector faz comparação referencial, isto é, se o endereço de memória for alterado ele gera uma nova renderização. [Olha o que fala as docs](https://react-redux.js.org/api/hooks#useselector).

Pra simplificar o GenericDrawerContainer se pode mover o componente OperatorParameter para outro componente e até tentar usar o [React.memo](https://pt-br.reactjs.org/docs/react-api.html#reactmemo) para memoizar o componente, mas o React usa comparação rasa (shallow equal) no React.memo, então acredito que você teria que passar um segundo parâmetro pra ele, que é uma nova função de comparação (pode usar o `isEqual` do lodash igual o useDeepSelector).

2021-07-30 12:49 UTC, fberanizo approved these changes
👍

2021-07-30 12:49 UTC, merged