Fix - Redirection to Login if Response Status is 302
platiagro/web-ui pull request #517
Opened 2021-08-16 21:15 UTC by LuanEdCosta

- Create `AuthExpired interceptor` inside the `services` folder
- Attach `AuthExpired interceptor` in **all API instances**
- Make all files inside the `services` folder return the axios instance
- Test if **all axios instances** have the `AuthExpired interceptor`

2021-08-16 21:16 UTC, LuanEdCosta commented
@fberanizo Teria como subir o código desta branch em um ambiente com login para testarmos se o que fiz funciona? Acredito que funciona sim porque simulei em um com login, mas nada como testar de verdade. :+1:

2021-08-17 12:37 UTC, fberanizo requested changes
Minha percepção é que adicionando o interceptor em cada service fica mais fácil de entender, porém mais verboso (com código duplicado).

Se tivesse uma função "fábrica" pra substituir o axios.create, e que já adicionasse o interceptor, acho ficaria mais enxuto o código. Essa sugestão tem uma desvantagem de tornar o desenvolvimento de futuros services anti-natural, principalmente pra novos devs (não se usaria o axios diretamente).

Bem...tem prós e contras. 
@schafferjrdev como você prefere?

2021-08-17 12:37 UTC, fberanizo commented on src/services/interceptors/AuthExpired.interceptor.js
> +};
@LuanEdCosta acho que acabou não funcionando como eu imaginava :(
Parece que o axios faz o redirect e termina num status 200 da tela de login:
![image](https://user-images.githubusercontent.com/1791381/129725139-d72f7582-fb9c-4b97-ac84-988b129b63a6.png)

Não sei se neste caso é um "error" e passa por este código (acho que não).

2021-08-17 12:59 UTC, LuanEdCosta commented on src/services/interceptors/AuthExpired.interceptor.js
> +};
Eu prefiro desse jeito mais explícito mesmo, mas podemos sim criar uma factory que usar o `axios.create()` e retorna a nova instância. @schafferjrdev A decisão é contigo :laughing:

2021-08-18 12:15 UTC, schafferjrdev commented on src/services/interceptors/AuthExpired.interceptor.js
> +};
@LuanEdCosta Com a sugestão do Fabio, a gente não estaria fazendo algo, em conceito, similar ao message? Pelo que entendi, seria só mais um código para iniciar uma instância do axios que é pré-configurada, não? 

De forma mais simples a decisão é ter menos código duplicado ou ser mais explícito. Acho que a vantagem principal seria se precisar mudar algo, ficaria em apenas um local de mudança.

2021-08-18 17:17 UTC, LuanEdCosta commented on src/services/interceptors/AuthExpired.interceptor.js
> +};
Vou criar a factory então. O único problema mesmo é a tipagem, mas vou ver se resolvo isso.

2021-08-18 19:54 UTC, LuanEdCosta commented
Agora **está funcionando** e consegui criar a **factory com as tipagens do axios**. @fberanizo Já pode testar no `awsplatiagro25` porque já implantei lá. Só uma coisa que achei não tão legal: o redirect demora um pouco, então as mensagens do antd ainda aparecem.

2021-08-18 20:10 UTC, fberanizo commented
> Agora **está funcionando** e consegui criar a **factory com as tipagens do axios**. @fberanizo Já pode testar no `awsplatiagro25` porque já implantei lá. Só uma coisa que achei não tão legal: o redirect demora um pouco, então as mensagens do antd ainda aparecem.

Acho que não tem muito problema do jeito que ficou. 
Será que dá pra transformar o resultado da request em uma exceção com mensagem de erro mais amigável?
Talvez a gente possa fazer um "cancel" na requisição para garantir que no service chegue exception. 
https://axios-http.com/docs/cancellation

O que você acha @LuanEdCosta ?

2021-08-19 13:17 UTC, fberanizo approved these changes
👍

2021-08-19 13:19 UTC, merged